#Site configuration
title: Fabian Densborn
name: Fabian Densborn
author: Fabian Densborn
work: Security Consultant @SEC Consult
certs: OSWE | OSCP | BSCP | eMAPT
year: 2023

# Navigation
nav1: "About me"
nav2: "Education"
nav3: "Work experience"
nav4: "Projects"

# Social Links
#facebook: fabian.densborn
twitter: densi_1101
#google: username
#instagram: username
#pinterest: username
linkedin: fabian-densborn-a14312212
#youtube: username
#spotify: username
#lastfm: username
github: densi97
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: fabi.densborn@gmail.com
