#Site configuration
title: Fabian Densborn
name:  Fabian Densborn
author: Fabian Densborn
work:  IT-Security Student @CISPA | OSCP
year: 2022

# Navigation
nav1: "About me"
nav2: "Education"
nav3: "Work experience"
nav4: "Projects"

# Social Links
#facebook: fabian.densborn
twitter:  densi_1101
#google: username
#instagram: username
#pinterest: username
linkedin: fabian-densborn-a14312212
#youtube: username
#spotify: username
#lastfm: username
github: densi97
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: desecprod@gmail.com

